#include "ht68.hpp"

instruc_t Instructions[HT68_last] =
{
  { "", 0 },
  { "nop",     0 },
  { "clrwdt1", 0 },
  { "halt",    CF_STOP },
  { "ret",     CF_STOP },
  { "reti",    CF_STOP },
  { "clrwdt2", 0 },
  { "mov",     CF_CHG1 },
  { "cpla",    CF_USE1 },
  { "cpl",     CF_USE1 | CF_CHG1 },
  { "sub",     CF_USE1 },
  { "subm",    CF_USE1 | CF_CHG1 },
  { "add",     CF_USE1 },
  { "addm",    CF_USE1 | CF_CHG1 },
  { "xor",     CF_USE1 },
  { "xorm",    CF_USE1 | CF_CHG1 },
  { "or",      CF_USE1 },
  { "orm",     CF_USE1 | CF_CHG1 },
  { "and",     CF_USE1 },
  { "andm",    CF_USE1 | CF_CHG1 },
  { "mov",     CF_USE1 },
  { "sbc",     CF_USE1 },
  { "ret",     CF_USE1 | CF_STOP },
  { "sub",     CF_USE1 },
  { "add",     CF_USE1 },
  { "xor",     CF_USE1 },
  { "or",      CF_USE1 },
  { "and",     CF_USE1 },
  { "mov",     CF_USE1 },
  { "sza",     CF_USE1 | CF_JUMP },
  { "sz",      CF_USE1 | CF_JUMP },
  { "swapa",   CF_USE1 },
  { "swap",    CF_USE1 | CF_CHG1 },
  { "sbc",     CF_USE1 },
  { "sbcm",    CF_USE1 | CF_CHG1 },
  { "adc",     CF_USE1 },
  { "adcm",    CF_USE1 | CF_CHG1 },
  { "inca",    CF_USE1 },
  { "inc",     CF_USE1 | CF_CHG1 },
  { "deca",    CF_USE1 },
  { "dec",     CF_USE1 | CF_CHG1 },
  { "siza",    CF_USE1 | CF_JUMP },
  { "siz",     CF_USE1 | CF_CHG1 | CF_JUMP },
  { "sdza",    CF_USE1 | CF_JUMP },
  { "sdz",     CF_USE1 | CF_CHG1 | CF_JUMP },
  { "rla",     CF_USE1 },
  { "rl",      CF_USE1 | CF_CHG1 },
  { "rra",     CF_USE1 },
  { "rr",      CF_USE1 | CF_CHG1 },
  { "rlca",    CF_USE1 },
  { "rlc",     CF_USE1 | CF_CHG1 },
  { "rrca",    CF_USE1 },
  { "rrc",     CF_USE1 | CF_CHG1 },
  { "itabrdc", CF_CHG1 },
  { "itabrdl", CF_CHG1 },
  { "tabrdc",  CF_CHG1 },
  { "tabrdl",  CF_CHG1 },
  { "snz",     CF_USE1 | CF_JUMP },
  { "daa",     CF_USE1 | CF_CHG1 },
  { "clr",     CF_CHG1 },
  { "set",     CF_CHG1 },
  { "call",    CF_USE1 | CF_CALL },
  { "jmp",     CF_USE1 | CF_JUMP | CF_STOP },
  { "set",     CF_USE1 | CF_CHG1 },
  { "clr",     CF_USE1 | CF_CHG1 },
  { "snz",     CF_USE1 | CF_JUMP },
  { "sz",      CF_USE1 | CF_JUMP },
};

const char *const ht68_autocmt[HT68_last] =
{
  "",
  "No operation",
  "Clear watchdog timer stage 1",
  "Stop CPU until interrupt/reset",
  "Return from subroutine",
  "Return from interrupt",
  "Clear watchdog timer stage 2",
  "Move accumulator to direct memory",
  "Complement direct memory into accumulator",
  "Complement direct memory",
  "Subtract direct memory from accumulator",
  "Subtract accumulator from direct memory",
  "Add direct memory to accumulator",
  "Add accumulator to direct memory",
  "XOR direct memory with accumulator",
  "XOR accumulator into direct memory",
  "OR direct memory with accumulator",
  "OR accumulator into direct memory",
  "AND direct memory with accumulator",
  "AND accumulator into direct memory",
  "Move direct memory to accumulator",
  "Subtract immediate and carry from accumulator",
  "Return and load accumulator immediate",
  "Subtract immediate from accumulator",
  "Add immediate to accumulator",
  "XOR immediate with accumulator",
  "OR immediate with accumulator",
  "AND immediate with accumulator",
  "Move immediate to accumulator",
  "Skip next instruction when direct memory zero-test (A form) succeeds",
  "Skip next instruction when direct memory is zero",
  "Swap nibbles in direct memory and load accumulator",
  "Swap nibbles in direct memory",
  "Subtract direct memory and carry from accumulator",
  "Subtract accumulator and carry into direct memory",
  "Add direct memory and carry to accumulator",
  "Add accumulator and carry into direct memory",
  "Increment direct memory and load accumulator",
  "Increment direct memory",
  "Decrement direct memory and load accumulator",
  "Decrement direct memory",
  "Increment direct memory and skip if result copied to accumulator is zero",
  "Increment direct memory and skip if result is zero",
  "Decrement direct memory and skip if result copied to accumulator is zero",
  "Decrement direct memory and skip if result is zero",
  "Rotate left direct memory through carry into accumulator",
  "Rotate left direct memory through carry",
  "Rotate right direct memory through carry into accumulator",
  "Rotate right direct memory through carry",
  "Rotate left direct memory into carry and accumulator",
  "Rotate left direct memory into carry",
  "Rotate right direct memory into carry and accumulator",
  "Rotate right direct memory into carry",
  "Indirect table read code byte to direct memory",
  "Indirect table read low byte to direct memory",
  "Table read code byte to direct memory",
  "Table read low byte to direct memory",
  "Skip next instruction when direct memory is non-zero",
  "Decimal adjust direct memory",
  "Clear direct memory",
  "Set direct memory",
  "Call absolute code address",
  "Jump to absolute code address",
  "Set direct memory bit",
  "Clear direct memory bit",
  "Skip next instruction when direct memory bit is non-zero",
  "Skip next instruction when direct memory bit is zero",
};

const char *idaapi ht68_get_autocmt(const insn_t &insn)
{
  if (insn.itype <= HT68_null || insn.itype >= HT68_last)
    return nullptr;
  return ht68_autocmt[insn.itype];
}
